# Site settings
course_name: DA623 Computing with Signals
course_description: "This is a course meant for students who intend to learn signal processing from an interdisciplinary perspective. The course will provide the students with an understanding of signals, modern signal processing techniques and machine learning concepts. A student completing the course will be able to design and discuss solutions to real-world problems in the areas of audio, image, brain-computer interfacing, and atmospheric applications."
course_semester: "Jan-May 2023"

baseurl: "/da623" # the subpath of your site, e.g. /blog/
url: "http://neerajww.github.io/" # the base hostname & protocol for your site

schoolname: "MFSDSAI, IITG"
schoolurl: "https://www.iitg.ac.in/dsai/home"
#twitter_username: username 

address: |
    Mehta Family School of Data Science and Artificial Intelligence
    IIT Guwahati, India

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
